// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package users

import ()

type User struct {
	ID             int32
	Username       string
	Email          *string
	HashedPassword *string
	IsActive       *bool
	IsSuperuser    *bool
}
