// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package users

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (
  username,
  email,
  hashed_password,
  is_active,
  is_superuser
) values (
  $1, $2, $3, $4, $5
) returning id, username, email, hashed_password, is_active, is_superuser
`

type CreateUserParams struct {
	Username       string
	Email          *string
	HashedPassword *string
	IsActive       *bool
	IsSuperuser    *bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.IsActive,
		arg.IsSuperuser,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
	)
	return i, err
}
